# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "tweetshrink"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Logan Koester"]
  s.date = "2013-06-05"
  s.description = "Ruby interface to the TweetShrink API"
  s.email = "logan@logankoester.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.textile"
  ]
  s.files = [
    "LICENSE",
    "README.textile",
    "Rakefile",
    "VERSION.yml",
    "features/steps/tweetshrink_steps.rb",
    "features/support/env.rb",
    "features/tweetshrink.feature",
    "lib/tweetshrink.rb",
    "spec/spec_helper.rb",
    "spec/tweetshrink_spec.rb",
    "tweetshrink.gemspec"
  ]
  s.homepage = "http://github.com/logankoester/tweetshrink"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "API Wrapper for TweetShrink"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

